<!DOCTYPE html>
<html>
    <meta charset="utf-8">
    <head>
        <?php include_once COMMON_TEMPLATES_DIR . 'head.phtml'; ?>
    </head>
    <body>
        <header>
            <?php include_once COMMON_TEMPLATES_DIR . 'navigation.phtml'; ?>
        </header>
        <div class="content">
            <p>I would like a couple of working example PHP files that do the following database tasks using PDO.</p>
            <ol>
                <li>add new form data from page to database, with and with out check if already exists or not.</li>
                <li>
                    page from database X number of results (changeable exp: 10, 20, 50, All) with page links(First Prev 1 2 3 Next Last), with edit / delete option. live searching. ability to sort by column.
                </li>
            </ol>
        </div>
    </body>
</html>