<!DOCTYPE html>
<html>
    <head>
        <?php include_once COMMON_TEMPLATES_DIR . 'head.phtml'; ?>
        <script type="text/javascript" src="/assets/js/userlist.js"></script>
    </head>
    <body>
    <header>
        <?php include_once COMMON_TEMPLATES_DIR . 'navigation.phtml'; ?>
    </header>
    <div class="content">
        <div class="search">
            <form action="" method="post">
                <label for="search">Search</label>
                <input type="text" id="search" name="search" value="<?php if (isset($search)) echo $search; ?>" placeholder="Type name here..."/>
                <input type="submit" value="Go!" />
            </form>
        </div>
        <div class="controls">
            <form action="" method="post">
                <label for="num_per_page">Results On Page</label>
                <input type="hidden" name="search" value="<?php if (isset($search)) echo $search; ?>" />
                <select name="num_per_page" id="num_per_page">
                    <?php foreach (array('10', '20', '50', 'All') as $num) { ?>
                        <option value="<?php echo $num; ?>"
                            <?php if (isset($num_per_page) && $num === $num_per_page) echo 'selected="selected"'; ?>>
                            <?php echo $num; ?>
                        </option>
                    <?php } ?>
                </select>
            </form>
            <ul>
                <li><a href="/user/">First</a></li>
                <li><a href="/user/">Previous</a></li>
                <li><a href="/user/">1</a></li>
                <li><a href="/user/">2</a></li>
                <li><a href="/user/">3</a></li>
                <li><a href="/user/">Next</a></li>
                <li><a href="/user/">Last</a></li>
            </ul>
        </div>
        <table>
            <caption><h1>User List</h1></caption>
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Description</th>
                    <th>Level</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($users as $user) { ?>
                    <tr>
                        <td><?php echo $user->username; ?></td>
                        <td><?php echo $user->description; ?></td>
                        <td><?php echo $user->level; ?></td>
                        <td>
                            <a href="/user/delete?id=<?php echo $user->id ?>">Delete</a>
                            /
                            <a href="/user/edit?id=<?php echo $user->id ?>">Edit</a>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    </body>
</html>